### PR TITLE
Create Divjot121.md

### PR DESCRIPTION
**Pull request by Divjot121**

### CODE REVIEW

**Review by caio11pessoa — APPROVED** [review]

**Comment by Divjot121** [comment]
Sir It Is Not Counted In Hacktoberfest

Divjot Singh Arora

**Comment by Divjot121** [comment]
Divjot Singh Arora

**Comment by caio11pessoa** [comment]
I know, but, it can help to merge faster, I hope.

**Comment by caio11pessoa** [comment]
ok, now I see, that repository has been excluded.

**Comment by Divjot121** [comment]
So now What Can I Do

Divjot Singh Arora

**Comment by caio11pessoa** [comment]
You can looking for others repositorys with the tag. If you want, I can help you to find.
Send me a email, caio11pessoa@gmail.com.

**Pull request merged**
