### PR TITLE
Added my portfolio, and created readme file with necessary information

### PR DESCRIPTION
**Pull request by Anikalp1**
**_I have added necessary documents for portfolio, and added a readme file and required images._**
hacktoberfest

**Preview of my readme file:** 
Screenshot (81)

Screenshot (82)

### CODE REVIEW

**Review by kishanrajput23 — CHANGES_REQUESTED** [review]
Please remove the content from `README.md` file is present in `Basic Portfolio` folder. 

After removing go to your-username folder then please check your README.md file because screenshots are not visible it just showing a link.

**Comment by Anikalp1** [comment]
@kishanrajput23 I have updated it, please review.

**Review by kishanrajput23 — CHANGES_REQUESTED** [review]
Screenshot_2022-09-30-21-33-45-540_com android chrome

See this is the problem your images are not visible

I have checked your readme file and there is a mistake you have given the path of images according to vs code that's why here on github it's not visible so you can do one thing just open your readme file one tab and images that your uploaded on github in another tab now do this


[Screenshot 1](paste link) 

For pasting link just right click on screenshot1 image and choose copy address link then paste it given brackets

Hope you understand... 
If any doubts arises then feel free to comment on this PR. I'll guide you.

**Comment by Anikalp1** [comment]
@kishanrajput23 okayy, I got it, will be changing accordingly, right now

**Comment by Anikalp1** [comment]
@kishanrajput23  Finally updated screenshots successfully, thanks for guidance.

**Review by kishanrajput23 — APPROVED** [review]

**Pull request closed without merging**
