### PR TITLE
Added my first Blog

### PR DESCRIPTION
**Pull request by lakshay451**
I have added my first blog which is based on personality development.

### CODE REVIEW

**Comment by kishanrajput23** [comment]
Hii buddy, 
It would be great if you can add 2-3 more points in your blogs so that it doesn't look like a paragraph or note.

**Comment by lakshay451** [comment]
Okay... Will do

**Review by kishanrajput23 — CHANGES_REQUESTED** [review]
Okay bro please do changes ASAP.

**Comment by lakshay451** [comment]
Please check it now

**Review by kishanrajput23 — APPROVED** [review]

**Pull request merged**
