### PR TITLE
Ankit07kumar11 tic tac toe

### PR DESCRIPTION
**Pull request by Ankit07kumar11**
hi bhaiya, i am from your youtube videos, i have stared the repository and added the code and readme files as shown in video

### CODE REVIEW

**Comment by Ankit07kumar11** [comment]
please merge this pull request in the 1st october so it can be counted as my 1st pull request

**Review by kishanrajput23 — CHANGES_REQUESTED** [review]
Please check instructions given in tic tac toe issue then only do the changes currently your files are not adhering the rules given in created issue. 

Please fix that then only I'd be able to approvw it.

**Review by kishanrajput23 — CHANGES_REQUESTED** [review]
Brother have you read the rules? 

Under `Tic Tac Toe` folder create a new folder of your username. 

For that under tic tac toe click on ade file then create new file then type your username then press / then you'll directly hum into this folder now you'll again get a box to enter something. 

Now type README.md then scroll down click on commit. 
Now again click on add file then upload your code file give proper commit mesage. 

Now add screenshots of your project in README.md file and for that click on README.md file and then drag a screenshots from your pc and drop there on README.md file. 


Then commit. 

Once done with this update my via commenting on PR

**Comment by Ankit07kumar11** [comment]
hii bhaiya, please  can you preview changes made by me.

**Review by kishanrajput23 — APPROVED** [review]

**Comment by Ankit07kumar11** [comment]
bhaiya its shows that your pr/mr submitted to a repository which have been excluded from hacktober fest

**Comment by kishanrajput23** [comment]
can you please share screen shots brother

**Pull request merged**
