### PR TITLE
Add TechCity Blog

### PR DESCRIPTION
**Pull request by Harshal2502**
This is a blog on the topic of top tech cities of India and how India is becoming a giant hub for international companies. If you wanna get a job in tech fields, these cities provide the best value in the entire India.

### CODE REVIEW

**Review by kishanrajput23 — COMMENTED** [review]
Hello @Harshal2502 
The blog was good but there are few things you need to change. 

1. Fix the alignment of texts because whole has no alignments. 
2. Please re-upload the picture 1, 2 and 5 because these 3 pics are half cut and also not looking good. 

Hope you will make changes soon.

**Comment by Harshal2502** [comment]
should I make another pull request after making changes?

**Comment by kishanrajput23** [comment]
No you don't need to make another PR just do changes what I said and new changes automatically reflects over here.

**Comment by Harshal2502** [comment]
@kishanrajput23 I hope everything is okay with my blog now, please let me know if you find anything to change..

**Comment by Harshal2502** [comment]
Please approve the PR otherwise..

**Review by kishanrajput23 — CHANGES_REQUESTED** [review]
Bro you made mistakes again

1. Why did you add pics in the `Blogs` folder please delete it. 
2. The simple way to do this is open readme.md file and drag & drop the images where you can want to add that particular images. Using this trick you don't have to upload pics in folder and adding links in readme. 

Please change it.

**Comment by Harshal2502** [comment]
@kishanrajput23 Please check now

**Review by kishanrajput23 — CHANGES_REQUESTED** [review]
Screenshot_2022-09-29-14-31-41-319_com android chrome

Again you made mistake. 

See now just open your readme.md file and wherever you want to add pics just drag and drop that pic from your pc and upload it in your readme.md file. 


You can take help from google as well.

**Comment by Harshal2502** [comment]
@kishanrajput23 I worked on it and I think it's working fine, Please let me know if any changes required

**Review by kishanrajput23 — APPROVED** [review]
Great you have done it :100:

**Comment by Harshal2502** [comment]
Thanks for merging my PR..

But why it isn't showing here?
image

**Pull request merged**
